# -*- coding: utf-8 -*-
"""even_fibonacci_sum .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBQxm078OE0q7-SaF1PQaIh9O28mBO0O

# Even fibonacci

**Even Fibonacci**
Cada nuevo término de la secuencia de Fibonacci se genera sumando los dos términos anteriores. Al comenzar con 1 y 2, los primeros 10 términos serán:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Al considerar los términos en la secuencia de Fibonacci cuyos valores no exceden los cuatro millones, encuentre la suma de los términos pares.
"""

def even_fibonacci_sum ():
  prev = 1
  curr = 2
  total_sum = 0

  while curr <= 4000000:
    if curr % 2 == 0:
      total_sum += curr
  
    prev, curr = curr, prev + curr

  return total_sum

result = even_fibonacci_sum()

print (result)

import json

resulta_data = {
    "even_fibonacci_sum" : result
}

with open ("prediction.json", "w") as file:
  json.dump (resulta_data, file)